### ISSUE TITLE
[POST] api/user/login

### ISSUE THREAD

**Issue by KimWonJun** [Team-JustGo/Server_For-Competition#10]
로그인 후 메인 페이지 정보 제공하는 기능

- [x] 처음 로그인시 고유값 얻어서 DB에 저장하기
- [x] 이미 로그인 한 유저일 시 유저 구별하기
- [x] 메인페이지 유저 정보 주기

**Comment by by09115** [comment]
Response를 어디서 받아와야 할지 몰라서 그냥 냅뒀어요! 추후수정할게요!!!

**Comment by by09115** [comment]
user/login을 완료함에 따라 이 이슈를 닫습니다.
